[package]

name = "blobby_volley"
version = "0.0.1"
authors = [ "Grzegorz Swirski <grzegorz@swirski.name>" ]

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"

[dependencies.gl]

[[bin]]

name = "blobby"
